const express = require('express');
const { readDb, writeDb, getUser } = require('../lib/db');
const { id, nowIso, clean } = require('../lib/utils');
const { publicUser } = require('../lib/shape');
const { result, assertTurn } = require('../lib/games');
const { notifyUser, gameName } = require('../lib/push');
const router = express.Router();

router.get('/dialogs', (req, res) => { const db = readDb(); const user = getUser(db, req.query.userId); res.json({ dialogs: dialogs(db, user.id) }); });
router.post('/dialogs', (req, res) => { const db = readDb(); const user = getUser(db, req.body.userId); const target = getUser(db, req.body.targetId); if (blocked(db, user.id, target.id)) return res.status(403).json({ error: 'Диалог недоступен' }); if (user.id === target.id) return res.status(400).json({ error: 'Нельзя написать себе' }); let dialog = findDialog(db, user.id, target.id); if (!dialog) { dialog = { id: id('dialog'), participantIds: [user.id, target.id], createdAt: nowIso() }; db.dialogs.push(dialog); writeDb(db); } res.json({ dialog }); });
router.get('/dialogs/:id/messages', (req, res) => { const db = readDb(); const user = getUser(db, req.query.userId); const dialog = requireDialog(db, req.params.id, user.id, res); if (!dialog) return; res.json({ messages: messages(db, dialog.id, user.id) }); });
router.post('/dialogs/:id/messages', (req, res) => { const db = readDb(); const user = getUser(db, req.body.userId); const dialog = requireDialog(db, req.params.id, user.id, res); if (!dialog) return; const otherId = dialog.participantIds.find((x) => x !== user.id); if (blocked(db, user.id, otherId)) return res.status(403).json({ error: 'Пользователь заблокирован' }); const type = req.body.type || 'text'; db.messages.push({ id: id('msg'), dialogId: dialog.id, userId: user.id, type, text: clean(req.body.text), mediaUrl: clean(req.body.mediaUrl), mediaType: type, createdAt: nowIso() }); notifyUser(db, otherId, { title: user.name || 'Миг', body: messageBody(type, req.body.text), data: { type: 'message', dialogId: dialog.id } }); writeDb(db); res.json({ ok: true }); });
router.post('/dialogs/:id/games', (req, res) => { const db = readDb(); const user = getUser(db, req.body.userId); const dialog = requireDialog(db, req.params.id, user.id, res); if (!dialog) return; const opponentId = dialog.participantIds.find((x) => x !== user.id); if (blocked(db, user.id, opponentId)) return res.status(403).json({ error: 'Игра недоступна' }); const game = { id: id('game'), dialogId: dialog.id, type: req.body.gameType || 'cups', creatorId: user.id, opponentId, status: 'pending_acceptance', createdAt: nowIso() }; db.games.push(game); db.messages.push({ id: id('msg'), dialogId: dialog.id, userId: user.id, type: 'game', gameId: game.id, createdAt: nowIso() }); notifyUser(db, opponentId, { title: 'Приглашение в игру', body: `${user.name || 'Пользователь'}: ${gameName(game.type)}`, data: { type: 'game', dialogId: dialog.id, gameId: game.id } }); writeDb(db); res.json({ game }); });
router.post('/games/:id/accept', (req, res) => updateGame(req, res, (g, user, db) => { if (blocked(db, g.creatorId, g.opponentId)) throw new Error('Игра недоступна'); if (g.status !== 'pending_acceptance') throw new Error('Игра уже началась'); if (g.opponentId !== user.id) throw new Error('Подтвердить должен собеседник'); g.status = 'creator_turn'; notifyUser(db, g.creatorId, { title: 'Игра принята', body: `${user.name || 'Собеседник'} принял игру`, data: { type: 'game', dialogId: g.dialogId, gameId: g.id } }); }));
router.post('/games/:id/decline', (req, res) => updateGame(req, res, (g, user, db) => { if (!isParticipant(g, user.id)) throw new Error('Нет доступа к игре'); if (g.status !== 'pending_acceptance') throw new Error('Игру уже нельзя отклонить'); g.status = 'declined'; notifyUser(db, g.creatorId, { title: 'Игра отклонена', body: `${user.name || 'Собеседник'} отклонил игру`, data: { type: 'game', dialogId: g.dialogId, gameId: g.id } }); }));
router.post('/games/:id/move', (req, res) => updateGame(req, res, (g, user, db) => { if (blocked(db, g.creatorId, g.opponentId)) throw new Error('Игра недоступна'); if (!isParticipant(g, user.id)) throw new Error('Нет доступа к игре'); const key = assertTurn(g, user.id); if (g[key]) throw new Error('Вы уже сделали ход'); g[key] = String(req.body.choice); g.status = key === 'creatorChoice' ? 'opponent_turn' : 'finished'; if (g.status === 'finished') g.result = result(g); notifyGameMove(db, g, user.id); }));
function dialogs(db, userId) { return db.dialogs.filter((d) => d.participantIds.includes(userId) && !blocked(db, userId, d.participantIds.find((x) => x !== userId))).map((d) => { const otherId = d.participantIds.find((x) => x !== userId); const last = db.messages.filter((m) => m.dialogId === d.id && m.status !== 'deleted').slice(-1)[0]; return { ...d, user: publicUser(db.users.find((u) => u.id === otherId)), lastText: last?.type === 'game' ? 'Игра' : last?.text || (last?.type === 'photo' ? 'Фото' : last?.type === 'video' ? 'Видео' : '') }; }); }
function messages(db, dialogId) { return db.messages.filter((m) => m.dialogId === dialogId && m.status !== 'deleted').map((m) => m.type === 'game' ? { ...m, game: db.games.find((g) => g.id === m.gameId) } : m); }
function findDialog(db, a, b) { return db.dialogs.find((d) => d.participantIds.includes(a) && d.participantIds.includes(b)); }
function requireDialog(db, id, userId, res) { const d = db.dialogs.find((x) => x.id === id); if (!d || !d.participantIds.includes(userId)) { res.status(403).json({ error: 'Нет доступа к диалогу' }); return null; } return d; }
function blocked(db, a, b) { const ua = db.users.find((u) => u.id === a); const ub = db.users.find((u) => u.id === b); return ua?.status === 'blocked' || ub?.status === 'blocked' || ua?.blockedUserIds?.includes(b) || ub?.blockedUserIds?.includes(a); }
function isParticipant(g, userId) { return g.creatorId === userId || g.opponentId === userId; }
function updateGame(req, res, fn) { try { const db = readDb(); const user = getUser(db, req.body.userId); const game = db.games.find((g) => g.id === req.params.id); if (!game) return res.status(404).json({ error: 'game not found' }); fn(game, user, db); game.updatedAt = nowIso(); writeDb(db); res.json({ game }); } catch (e) { res.status(400).json({ error: e.message }); } }
function messageBody(type, text) { if (type === 'photo') return 'Отправил фото'; if (type === 'video') return 'Отправил видео'; return clean(text, 'Новое сообщение'); }
function notifyGameMove(db, g, actorId) { const otherId = actorId === g.creatorId ? g.opponentId : g.creatorId; const body = g.status === 'finished' ? 'Игра завершена' : 'Ваш ход в игре'; notifyUser(db, otherId, { title: gameName(g.type), body, data: { type: 'game', dialogId: g.dialogId, gameId: g.id } }); }
module.exports = router;
